name: Publish Hubble
on:
  push:
    tags:
      - '@farcaster/hubble@*'

concurrency: package-tags

jobs:
  publish-docker-image:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Log in so we can push the image layers + tags to Docker Hub
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - uses: depot/setup-action@v1

      # Install Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Create and use a new builder instance
      - name: Create builder
        run: |
          docker buildx create --name mybuilder --use
          docker buildx inspect --bootstrap

      - run: ./scripts/publish-image.sh
        shell: bash